INSERT INTO artist (name) VALUES ('Tauski');
COMMIT;
INSERT INTO album (name, year, artist_id) VALUES ('Charlotta', 1989, 1);
COMMIT;
INSERT INTO track (track_number, name, track_length, album_id) VALUES (1, 'Haavemaa (Liberta)', 243, 1);
INSERT INTO track (track_number, name, track_length, album_id) VALUES (2, 'Sydämen Piirsit', 164, 1);
INSERT INTO track (track_number, name, track_length, album_id) VALUES (3, 'Nina (Sweet, Sweet Music)', 210, 1);
INSERT INTO track (track_number, name, track_length, album_id) VALUES (4, 'Uuteen Elämään', 168, 1);
INSERT INTO track (track_number, name, track_length, album_id) VALUES (5, 'Teen Mitä Vaan', 176, 1);
INSERT INTO track (track_number, name, track_length, album_id) VALUES (6, 'Kun Rakastunut On (Give A Little Love)', 183, 1);
INSERT INTO track (track_number, name, track_length, album_id) VALUES (7, 'Auringonlaskun Katu', 189, 1);
INSERT INTO track (track_number, name, track_length, album_id) VALUES (8, 'Käy Mun Vierelläin (Hand In Hand)', 254, 1);
INSERT INTO track (track_number, name, track_length, album_id) VALUES (9, 'Charlotta', 187, 1);
INSERT INTO track (track_number, name, track_length, album_id) VALUES (10, 'Se Unohtuu (Elle Imagine)', 248, 1);
INSERT INTO track (track_number, name, track_length, album_id) VALUES (11, 'Puistotie', 216, 1);
INSERT INTO track (track_number, name, track_length, album_id) VALUES (12, 'Jään', 207, 1);
INSERT INTO track (track_number, name, track_length, album_id) VALUES (13, 'Rakkauden Maailma', 220, 1);